name: Deploy Roulette Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to remote server
      run: |
        ssh -o StrictHostKeyChecking=no 3.139.139.13 '
          cd miniCasinoBack/roulette-backend &&
          docker-compose down &&
          git pull origin main &&
          docker-compose up -d
        '
