name: Deploy Roulette Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Stack
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USER}}
        key: ${{secrets.SSH_PRIVATE_KEY}}
        script: |
          #!/bin/bash
          cd miniCasinoBack/roulette-backend &&
          docker-compose down &&
          git pull origin main &&
          docker-compose up -d
